title: Facility Location Problem

theme: jekyll-theme-minimal

#External navigation links
nav_links:
  - title: "Home"
    url: "https://am-msba.github.io/Portfolio/"
  - title: "ML Prediction Model"
    url: "https://am-msba.github.io/Machine_Learning_Prediction_Project/"
  - title: "AWS Prediction"
    url: "https://am-msba.github.io/Amazon_AWS_Predictor/"
